name: Rust CI

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-dashboard:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install SDL2 dependencies
      run: sudo apt-get update && sudo apt-get install libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev
    - name: Setup Rust and Cargo
      uses: moonrepo/setup-rust@v1.1.0
    - name: Build
      run: cargo build --release --verbose
